name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Archive Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sb1-artifact
          path: target/
        
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and analyze with SonarQube
        run: mvn -B verify -DskipTests sonar:sonar -Dsonar.projectKey=Swathi3801_sb1 -Dsonar.organization=swathi3801 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONARCLOUD_TOKEN
        env:
          GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GIT_HUB_TOKEN }}
      
      - name: Build and Push Docker Image to GitHub Container Registry
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name | lower }}swathicontainer:latest .
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name | lower }}swathicontainer:latest
        env:
          DOCKER_BUILDKIT: 1
